In [101]:
import pandas as pd
stops = pd.read_csv("data_sncf/stops.csv")
stop_times = pd.read_csv("data_sncf/stop_times.csv")
trips = pd.read_csv("data_sncf/trips.csv")

In [102]:
stop_complete_info = stops.merge(stop_times,on="stop_id")

Tout d'abord on fusionne les tables stops et stop_times afin d'obtenir une table avec des informations plus complète tel quel le trip_id

In [103]:
stop_complete_info.head()

,stop_id,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,trip_id,arrival_time,departure_time,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled
0,StopPoint:OCECar TER-87381509,Gare de Mantes-la-Jolie,NaN,48.989687,1.703294,NaN,NaN,0,StopArea:OCE87381509,OCESN037071R0100119847,23:05:00,23:05:00,0,NaN,0,0,NaN
1,StopPoint:OCECar TER-87381509,Gare de Mantes-la-Jolie,NaN,48.989687,1.703294,NaN,NaN,0,StopArea:OCE87381509,OCESN438003R0200234693,22:00:00,22:00:00,0,NaN,0,0,NaN
2,StopPoint:OCECar TER-87381509,Gare de Mantes-la-Jolie,NaN,48.989687,1.703294,NaN,NaN,0,StopArea:OCE87381509,OCESN438004R0200234694,11:29:00,11:29:00,3,NaN,0,0,NaN
3,StopPoint:OCECar TER-87415604,Gare de Vernon-Giverny,NaN,49.091286,1.478363,NaN,NaN,0,StopArea:OCE87415604,OCESN037071R0100119847,23:35:00,23:35:00,1,NaN,0,0,NaN
4,StopPoint:OCECar TER-87415620,Gare de Gaillon-Aubevoye,NaN,49.174632,1.352518,NaN,NaN,0,StopArea:OCE87415620,OCESN037071R0100119847,23:55:00,23:55:00,2,NaN,0,0,NaN

In [104]:
stop_trip_complete_info = stop_complete_info.merge(trips,on="trip_id")

A partir de là on fusionne notre table stop_trip_complete avec la table des trips afin d'obtenir les informations  complète sur un trip et ses stops

In [105]:
stop_trip_complete_info.head()

,stop_id,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,trip_id,...,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,route_id,service_id,trip_headsign,direction_id,block_id,shape_id
0,StopPoint:OCECar TER-87381509,Gare de Mantes-la-Jolie,NaN,48.989687,1.703294,NaN,NaN,0,StopArea:OCE87381509,OCESN037071R0100119847,...,NaN,0,0,NaN,OCE1506035,9939,37071,1,NaN,NaN
1,StopPoint:OCECar TER-87415604,Gare de Vernon-Giverny,NaN,49.091286,1.478363,NaN,NaN,0,StopArea:OCE87415604,OCESN037071R0100119847,...,NaN,0,0,NaN,OCE1506035,9939,37071,1,NaN,NaN
2,StopPoint:OCECar TER-87415620,Gare de Gaillon-Aubevoye,NaN,49.174632,1.352518,NaN,NaN,0,StopArea:OCE87415620,OCESN037071R0100119847,...,NaN,0,0,NaN,OCE1506035,9939,37071,1,NaN,NaN
3,StopPoint:OCECar TER-87415877,Gare de Val-de-Reuil,NaN,49.275399,1.224609,NaN,NaN,0,StopArea:OCE87415877,OCESN037071R0100119847,...,NaN,0,0,NaN,OCE1506035,9939,37071,1,NaN,NaN
4,StopPoint:OCECar TER-87411207,Gare de Oissel,NaN,49.343042,1.101821,NaN,NaN,0,StopArea:OCE87411207,OCESN037071R0100119847,...,NaN,0,0,NaN,OCE1506035,9939,37071,1,NaN,NaN

In [106]:
from_gare_de_l_est_before_ten = stop_trip_complete_info[(stop_trip_complete_info["stop_name"] == "Gare de Paris-Est") & (stop_trip_complete_info["departure_time"] <= "10:00:00")][["trip_id", "departure_time"]]

On récupère tout les trips ayant un arrêt à la gare de Paris-Est et dont l'horaire de départ est fixé avant 10:00 du matin

In [107]:
from_gare_de_l_est_before_ten.sort_values("departure_time")

                       trip_id departure_time
196429  OCESN839561F0800838467       05:42:00
196520  OCESN839551F3403438301       06:34:00
197345  OCESN839131F1201238020       06:36:00
197351  OCESN839131F0900938022       06:36:00
198430  OCESN839131F1301338019       06:36:00
...                        ...            ...
170228  OCESN839162F0900938089       09:55:00
170192  OCESN839162F0500538088       09:55:00
196783  OCESN839550F8108138273       09:57:00
94735   OCESN839550F7007038284       09:59:00
196792  OCESN839550F5305338270       09:59:00

[70 rows x 2 columns]

On peut donc voir qu'il y a 70 trains qui partent de la gare de l'est avant 10h. Le premier à 05:42 et le dernier à 09:59.